hw-39 - do homework
furfries1/js-pro pull request #7
Opened 2023-08-17 20:57 UTC by furfries1

2023-08-17 21:03 UTC, furfries1 commented
I accidentally pushed 39 & 40 homeworks in one PR

2023-08-19 07:46 UTC, AlexKolb97 commented on homework/src/components/Blog/Blog.tsx
> +    const getPosts = async () => {
It's better to have this function in a separate file called `helpers.ts`. Import it and use inside your component.

2023-08-19 07:49 UTC, AlexKolb97 commented on homework/src/components/SelectedPostContainer/SelectedPostContainer.tsx
> +    const getPosts = async () => {
See the comment above. By the way, you can pass a prop limit to the function and fetch a specific number of posts based on your need.

const fetchPosts(limit?: number) => {
  await fetch(`https://studapi.teachmeskills.by/blog/posts/?limit=${limit}`)
  // the rest of the code
}

2023-08-19 07:51 UTC, AlexKolb97 requested changes
Please fix the comments.

2023-08-21 15:52 UTC, merged